---
Parameters:
  RoleName:
    Type: String
    Default: 'crowdstrike-distributor-deploy-role'
    Description: 'Name of the IAM role to create'
  SecretStorageMethod:
    Type: String
    Default: ParameterStore
    Description: 'The method used to store the Falcon ClientId, ClientSecret, and Cloud for the CrowdStrike APIs.'
    AllowedValues:
      - 'ParameterStore'
      - 'SecretsManager'

Conditions:
  UseSecretsManager: !Equals [!Ref SecretStorageMethod, 'SecretsManager']

Resources:
  SsmAutomationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'ssm.amazonaws.com'
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonSSMAutomationRole'
        - !If
            - UseSecretsManager
            - 'arn:aws:iam::aws:policy/SecretsManagerReadWrite'
            - !Ref 'AWS::NoValue'
